### ISSUE TITLE
Python 3.7 and up requirement

### ISSUE THREAD

**Issue by rajeeja** [GWU-CFD/FlashKit#68]
Upgrading my python from 3.6 to 3.7 works. 
With python-3.6.13:

```
└─ $ ▶ python --version
Python 3.6.13 :: Anaconda, Inc.
└─ $ ▶ flashkit create xdmf --help
Traceback (most recent call last):
  File "/home/jain/.conda/envs/myenv/bin/flashkit", line 33, in <module>
    sys.exit(load_entry_point('flashkit', 'console_scripts', 'flashkit')())
  File "/home/jain/.conda/envs/myenv/bin/flashkit", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jain/.conda/envs/myenv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/jain/.conda/envs/myenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nfs/gce/projects/FLASH5/software/FlashKit/src/flashkit/__init__.py", line 4, in <module>
    from . import api as flash
  File "/nfs/gce/projects/FLASH5/software/FlashKit/src/flashkit/api/__init__.py", line 4, in <module>
    from . import build
  File "/nfs/gce/projects/FLASH5/software/FlashKit/src/flashkit/api/build/__init__.py", line 4, in <module>
    from ._simulation import simulation
  File "/nfs/gce/projects/FLASH5/software/FlashKit/src/flashkit/api/build/_simulation.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

The issue is like this one - https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future/52890129, where the resolution was to update python version.

**Comment by glentner** [comment]
Indeed, `annotations` was added in 3.7 I believe.

If I have a class:

```python
class Thing:

    @classmethod
    def new(cls) -> Thing:
        return cls()
```

You'll get a type error on that return type. The `__future__` import causes 'delayed' checking in 3.7 and 3.8. Python 3.9 this is the standard I think. Something like that anyway.

**Comment by alentner** [comment]
I think this issue is closed.

I currently support python 3.7 through python 3.10.

In the future python 3.7 will be dropped (either when a 3.8 only feature is needed or 3.7 is EOL).
